#include<stdio.h>
int main()
{
    int n,m,i,j,s,p=0,l=0,k;
    scanf("%d%d",&n,&m);
    int a[n][m];
    for(i=0;i<n;i++)
    {
        for(j=0;j<m;j++)
        {
            scanf("%d",&a[i][j]);
        }
    }
    for(i=0;i<n;i++)
    {
        s=0;
        for(j=0;j<m;j++)
        {
            s=s+a[i][j];
        }
        if(s>p)
        {
            p=s;
        }
    }
    for(j=0;j<m;j++)
    {
        k=0;
        for(i=0;i<n;i++)
        {
            k=k+a[i][j];
        }
        if(k>l)
        {
            l=k;
        }
    }
    if(l>p)
    {
        printf("%d",l);
    }
    else
    {
        printf("%d",p);
    }
}